GET http://localhost:3000/bank-accounts

###
GET http://localhost:3000/bank-accounts/13fa96a8-90c8-4690-a017-6001b6a9686a

###
POST http://localhost:3000/bank-accounts
Content-Type: application/json

{
    "account_number": "3333-33"
}

###
PATCH http://localhost:3000/bank-accounts/123
Content-Type: application/json

{
    "account_number": 1234
}

###
DELETE http://localhost:3000/bank-accounts/123

###
POST http://localhost:3000/bank-accounts/transfer
Content-Type: application/json

{
    "from": "1111-11",
    "to": "2222-22",
    "amount": 100
}

###
POST http://localhost:3000/users
Content-Type: application/json

{
    "name": "John Doe",
    "email": "john@mail.com"
}