GET http://localhost:3000/bank-accounts

###
GET http://localhost:3000/bank-accounts/ef313639-1624-4577-ab16-3f8b86ab70a5

###
POST http://localhost:3000/bank-accounts/transfer
Content-Type: application/json

{
    "from": "8417-65",
    "to": "3390-33",
    "amount": 50
}

###
POST http://localhost:3000/users
Content-Type: application/json

{
    "name": "John Doe",
    "email": "john@mail.com"
}