GET http://localhost:3000/bank-accounts

###
GET http://localhost:3000/bank-accounts/46d9680a-e9b7-46c1-ab90-083fdca42ce1

###
POST http://localhost:3000/bank-accounts/transfer
Content-Type: application/json

{
    "from": "1942-34",
    "to": "6027-42",
    "amount": 50
}

###
POST http://localhost:3000/users
Content-Type: application/json

{
    "name": "John Doe",
    "email": "john@mail.com"
}